from sqlalchemy import Column, String, Integer, Boolean, Float, ForeignKey
from ..main import Base

class Vehicle(Base):
    __tablename__ = "vehicles"

    id = Column("id", Integer, primary_key=True, autoincrement=True)
    model_year = Column("modelYear")
    chassis_number = Column("chassisNumber")
    license_plate = Column("licensePlate")
    initial_mileage = Column("initialMileage")
    first_mileage = Column("firstMileage")
    vtv_expiration = Column("vtvExpiration")
    district = Column("district")
    registration_date = Column("registrationDate")
    business_area = Column("businessArea")
    business_line = Column("businessLine")
    market_segment = Column("marketSegment")
    use_class = Column("useClass")
    expense_group = Column("expenseGroup")
    cost_center = Column("costCenter")
    version = Column("version")
    telemetry_capable = Column("telemetryCapable")
    document_date = Column("documentDate")
    kba_number = Column("kbaNumber")
    drivers_name = Column("driversName")
    last_mileage_updated = Column("lastMileageUpdated")
    display_model_brand = Column("displayModelBrand")
    integration_type = Column("integrationType")
    last_telemetry_status = Column("lastTelemetryStatus")
    have_maintenance_plan = Column("haveMaintenancePlan")
    have_price_table = Column("havePriceTable")
    gps_status = Column("gpsStatus")
    gps_origin = Column("gpsOrigin")
    active = Column("active")
    server_url = Column("serverUrl")