"""Initial Migration

Revision ID: 1ac4211a0eab
Revises: 
Create Date: 2026-09-25 11:31:13.208513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac4211a0eab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modelYear', sa.Integer(), nullable=True),
    sa.Column('chassisNumber', sa.String(), nullable=True),
    sa.Column('licensePlate', sa.String(), nullable=True),
    sa.Column('initialMileage', sa.Float(), nullable=True),
    sa.Column('firstMileage', sa.Float(), nullable=True),
    sa.Column('vtvExpiration', sa.String(), nullable=True),
    sa.Column('registrationDate', sa.String(), nullable=True),
    sa.Column('businessArea', sa.String(), nullable=True),
    sa.Column('businessLine', sa.String(), nullable=True),
    sa.Column('marketSegment', sa.String(), nullable=True),
    sa.Column('useClass', sa.Boolean(), nullable=True),
    sa.Column('expenseGroup', sa.String(), nullable=True),
    sa.Column('costCenter', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('telemetryCapable', sa.Boolean(), nullable=True),
    sa.Column('documentDate', sa.String(), nullable=True),
    sa.Column('kbaNumber', sa.String(), nullable=True),
    sa.Column('driversName', sa.String(), nullable=True),
    sa.Column('lastMileageUpdated', sa.Float(), nullable=True),
    sa.Column('displayModelBrand', sa.String(), nullable=True),
    sa.Column('integrationType', sa.String(), nullable=True),
    sa.Column('lastTelemetryStatus', sa.String(), nullable=True),
    sa.Column('haveMaintenancePlan', sa.Boolean(), nullable=True),
    sa.Column('havePriceTable', sa.Boolean(), nullable=True),
    sa.Column('gpsStatus', sa.String(), nullable=True),
    sa.Column('gpsOrigin', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('serverUrl', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('tripId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicleId', sa.String(), nullable=True),
    sa.Column('startTime', sa.String(), nullable=True),
    sa.Column('durationValue', sa.Float(), nullable=True),
    sa.Column('durationUnit', sa.String(), nullable=True),
    sa.Column('startAddress', sa.String(), nullable=True),
    sa.Column('endAddress', sa.String(), nullable=True),
    sa.Column('distanceValue', sa.Float(), nullable=True),
    sa.Column('distanceUnit', sa.String(), nullable=True),
    sa.Column('tripType', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('driver', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver'], ['users.id'], ),
    sa.PrimaryKeyConstraint('tripId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    op.drop_table('vehicles')
    op.drop_table('users')
    # ### end Alembic commands ###
