"""remove gps_origin field

Revision ID: ae2c5f56f2eb
Revises: 1ac4211a0eab
Create Date: 2026-09-25 13:25:52.496968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae2c5f56f2eb'
down_revision: Union[str, Sequence[str], None] = '1ac4211a0eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'gpsOrigin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('gpsOrigin', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
