"""add again gps_origin field

Revision ID: f23563d303d9
Revises: a08325828454
Create Date: 2026-09-25 13:30:38.114802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23563d303d9'
down_revision: Union[str, Sequence[str], None] = 'a08325828454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('gpsOrigin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'gpsOrigin')
    # ### end Alembic commands ###
